[package]
name = "emagick-rs"
version = "0.3.1"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
description = "Erlang interface to ImageMagick via Rust."
homepage = "https://github.com/nlfiedler/emagick.rs"
repository = "https://github.com/nlfiedler/emagick.rs.git"
readme = "README.md"
keywords = ["imagemagick", "erlang"]
license = "Apache-2.0"

[lib]
name = "emagick_rs"
crate-type = ["dylib"]

[dependencies.magick_rust]
git = "https://github.com/nlfiedler/magick-rust.git"
tag = "0.3.1"

[dependencies.ruster_unsafe]
git = "https://github.com/nlfiedler/ruster_unsafe.git"
tag = "0.2.2"

[dependencies]
libc = "0.2.4"
